Repository dell/dellemc-openmanage-ansible-modules, pull requests merged in 2025-06, with the labels that each got.

#888 [integration][redfish_event_subscription] - 17g support
  tests/integration/targets/idrac_redfish_event_subscription/tests/_get_server_generation.yml
  tests/integration/targets/idrac_redfish_event_subscription/tests/create-11853.yaml
  tests/integration/targets/idrac_redfish_event_subscription/tests/delete-11855.yaml
  tests/integration/targets/idrac_redfish_event_subscription/tests/invalid-11854.yaml
Labels: Ready for PR review

#878 Adding 17G support for idrac LC logs
  docs/modules/idrac_lifecycle_controller_logs.rst
  plugins/module_utils/idrac_redfish.py
  plugins/module_utils/idrac_utils/idrac_lifecycle_controller_logs_utils.py
  plugins/module_utils/logging_handler.py
  plugins/module_utils/utils.py
  plugins/modules/idrac_lifecycle_controller_logs.py
  tests/integration/targets/idrac_lifecycle_controller_logs/defaults/main.yaml
  tests/integration/targets/idrac_lifecycle_controller_logs/files/ansible_doc.txt
  tests/integration/targets/idrac_lifecycle_controller_logs/meta/main.yaml
  tests/integration/targets/idrac_lifecycle_controller_logs/tasks/main.yaml
  tests/integration/targets/idrac_lifecycle_controller_logs/tests/_helper.yml
  tests/integration/targets/idrac_lifecycle_controller_logs/tests/ansible_doc-11696.yaml
  tests/integration/targets/idrac_lifecycle_controller_logs/tests/invalid-11695.yaml
  tests/integration/targets/idrac_lifecycle_controller_logs/tests/job_wait_false-11694.yaml
  tests/integration/targets/idrac_lifecycle_controller_logs/tests/job_wait_true-11693.yaml
  tests/unit/plugins/module_utils/idrac_utils/test_bios_info.py
  tests/unit/plugins/module_utils/idrac_utils/test_controller_enclosure_info.py
  tests/unit/plugins/module_utils/idrac_utils/test_cpu_info.py
  tests/unit/plugins/module_utils/idrac_utils/test_idrac_lifecycle_controller_logs_utils.py
  tests/unit/plugins/module_utils/test_idrac_redfish.py
  tests/unit/plugins/module_utils/test_logging_handler.py
  tests/unit/plugins/modules/test_idrac_lifecycle_controller_logs.py
Labels: validation/completed, Ready for PR review

#875 Support for 17G idrac_diagnostics
  tests/integration/targets/idrac_diagnostics/defaults/main.yaml
  tests/integration/targets/idrac_diagnostics/files/ansible_doc.txt
  tests/integration/targets/idrac_diagnostics/meta/main.yaml
  tests/integration/targets/idrac_diagnostics/tasks/main.yaml
  tests/integration/targets/idrac_diagnostics/tests/_assert_job_status.yml
  tests/integration/targets/idrac_diagnostics/tests/_ensure_run.yml
  tests/integration/targets/idrac_diagnostics/tests/_get_job_details.yml
  tests/integration/targets/idrac_diagnostics/tests/_get_updated_idrac_date_time.yml
  tests/integration/targets/idrac_diagnostics/tests/_run_diagnostics_track.yml
  tests/integration/targets/idrac_diagnostics/tests/_run_no_wait.yml
  tests/integration/targets/idrac_diagnostics/tests/_verify_diag_file.yml
  tests/integration/targets/idrac_diagnostics/tests/_verify_export_http.yml
  tests/integration/targets/idrac_diagnostics/tests/ansible_doc-11641.yaml
  tests/integration/targets/idrac_diagnostics/tests/export_cifs-11644.yaml
  tests/integration/targets/idrac_diagnostics/tests/export_http-11646.yaml
  tests/integration/targets/idrac_diagnostics/tests/export_http_proxy-11648.yaml
  tests/integration/targets/idrac_diagnostics/tests/export_https-11647.yaml
  tests/integration/targets/idrac_diagnostics/tests/export_https_proxy-11643.yaml
  tests/integration/targets/idrac_diagnostics/tests/export_local-11642.yaml
  tests/integration/targets/idrac_diagnostics/tests/export_negative_scenarios-11649.yaml
  tests/integration/targets/idrac_diagnostics/tests/export_nfs-11645.yaml
  tests/integration/targets/idrac_diagnostics/tests/invalid_common_parameters-11639.yaml
  tests/integration/targets/idrac_diagnostics/tests/invalid_run-11640.yaml
  tests/integration/targets/idrac_diagnostics/tests/run_export_check_and_nomal_mode-11638.yaml
  tests/integration/targets/idrac_diagnostics/tests/run_express_force_job_wait-11634.yaml
  tests/integration/targets/idrac_diagnostics/tests/run_express_powercycle_without_scheduled_start_time_job_wait_true-11637.yaml
  tests/integration/targets/idrac_diagnostics/tests/run_extended_graceful_job_wait_false-11635.yaml
  tests/integration/targets/idrac_diagnostics/tests/run_job_wait-11651.yaml
  tests/integration/targets/idrac_diagnostics/tests/run_longrun_powercycle_scheduled_start_job_wait_false-11636.yaml
  tests/integration/targets/idrac_diagnostics/tests/run_no_job_wait-11650.yaml
  tests/integration/targets/idrac_diagnostics/vars/main.yaml
  tests/integration/targets/idrac_diagnostics/vars/main.yml
  tests/integration/targets/idrac_redfish_powerstate/tests/invalid-11862.yaml
Labels: Ready for PR review

#894 Updated codecov range
  .github/workflows/ansible-test.yml
  codecov.yml
Labels: Ready for PR review

#897 [Module][Integration][ome_session]: Added fix to invalid test for timeout for 4.4 OME Version
  tests/integration/targets/ome_session/tests/invalid.yaml
Labels: validation/completed, Ready for PR review

#898 [Module][idrac_system_erase] - 17G Support
  docs/modules/idrac_system_erase.rst
  plugins/modules/idrac_system_erase.py
  tests/integration/targets/idrac_system_erase/tests/__lc_status.yml
  tests/integration/targets/idrac_system_info/tests/_get_controller_details.py
  tests/unit/plugins/modules/test_idrac_system_erase.py
Labels: validation/completed, Ready for PR review

#903 fixed the bug for idrac_bios role
  plugins/modules/idrac_bios.py
  tests/unit/plugins/modules/test_idrac_bios.py
Labels: type/bug, validation/completed, Ready for PR review

#909 [Module] [Idrac_user]: defect fix
  plugins/modules/idrac_user.py
  tests/unit/plugins/modules/test_idrac_user.py
Labels: validation/completed, Ready for PR review

#908 [Module][Integration][idrac_certificates/ome_application_certificate]: Removing dependency for community.crypto
  tests/integration/targets/idrac_certificates/defaults/main.yaml
  tests/integration/targets/idrac_certificates/files/ansible_doc.txt
  tests/integration/targets/idrac_certificates/tasks/main.yaml
  tests/integration/targets/idrac_certificates/tests/_check_firmware_version_supported.yml
  tests/integration/targets/idrac_certificates/tests/_cleanup.yml
  tests/integration/targets/idrac_certificates/tests/_download_certificates.yml
  tests/integration/targets/idrac_certificates/tests/_helper_validate_export_certificates.yml
  tests/integration/targets/idrac_certificates/tests/_helper_validate_import_certificates.yml
  tests/integration/targets/idrac_certificates/tests/_wait_for_idrac_readiness.yml
  tests/integration/targets/idrac_certificates/tests/ansible_doc-11626.yaml
  tests/integration/targets/idrac_certificates/tests/generate_csr-11627.yaml
  tests/integration/targets/idrac_certificates/tests/generate_csr_4096-11899.yaml
  tests/integration/targets/idrac_certificates/tests/get_data_uri.yml
  tests/integration/targets/idrac_certificates/tests/invalid_scenarios-11629.yaml
  tests/integration/targets/idrac_certificates/tests/reset_https-11628.yaml
  tests/integration/targets/idrac_certificates/tests/validate_export_certificates-11624.yaml
  tests/integration/targets/idrac_certificates/tests/validate_export_custom_certificate-11633.yaml
  tests/integration/targets/idrac_certificates/tests/validate_import_certificates-11625.yaml
  tests/integration/targets/idrac_certificates/tests/validate_import_custom_certificate_with_passphrase-11631.yaml
  tests/integration/targets/idrac_certificates/tests/validate_import_custom_certificate_without_passphrase-11632.yaml
  tests/integration/targets/idrac_certificates/tests/validate_import_https_certificate_via_sslkey-11630.yaml
  tests/integration/targets/idrac_certificates/vars/main.yaml
  tests/integration/targets/ome_application_certificate/defaults/main.yaml
  tests/integration/targets/ome_application_certificate/files/ansible_doc.txt
  tests/integration/targets/ome_application_certificate/tasks/main.yaml
  tests/integration/targets/ome_application_certificate/tests/_download_certificates.yml
  tests/integration/targets/ome_application_certificate/tests/ansible_doc.yaml
  tests/integration/targets/ome_application_certificate/tests/generate_csr.yaml
  tests/integration/targets/ome_application_certificate/tests/generate_csr_san.yaml
  tests/integration/targets/ome_application_certificate/tests/invalid.yaml
  tests/integration/targets/ome_application_certificate/tests/invalid_san.yaml
  tests/integration/targets/ome_application_certificate/tests/upload_certificate_chain.yaml
Labels: Ready for PR review

#913 [Doc_update] Changelogs_9.12.2
  CHANGELOG.rst
  changelogs/changelog.yaml
  docs/README.md
  galaxy.yml
Labels: Ready for PR review

#911 [Module][ome_application_security_settings]: traceback error fix
  plugins/modules/ome_application_security_settings.py
  tests/unit/plugins/modules/test_ome_application_security_settings.py
Labels: validation/completed, Ready for PR review

#921 [Module][redfish_storage_volume]: Fixing issue with idempotent case related to deletion of VD
  plugins/modules/redfish_storage_volume.py
  tests/integration/targets/idrac_redfish_storage_volume/tests/delete_raid-11745.yaml
  tests/unit/plugins/modules/test_redfish_storage_volume.py
Labels: validation/completed, Ready for PR review
