Repository dell/dellemc-openmanage-ansible-modules, pull requests merged in 2025-08, with the labels that each got.

#939 [module][ome_identity_pool][ECS02C-243] OME:4.5 Qualification
  playbooks/ome/ome_identity_pool.yml
  plugins/modules/ome_identity_pool.py
  tests/integration/targets/ome_identity_pool/defaults/main.yaml
  tests/integration/targets/ome_identity_pool/files/ansible_doc.txt
  tests/integration/targets/ome_identity_pool/tasks/main.yaml
  tests/integration/targets/ome_identity_pool/tests/ansible_doc-12531.yaml
  tests/integration/targets/ome_identity_pool/tests/create-12593.yaml
  tests/integration/targets/ome_identity_pool/tests/delete-12576.yaml
  tests/integration/targets/ome_identity_pool/tests/invalid-12623.yaml
  tests/integration/targets/ome_identity_pool/tests/modify-12573.yaml
  tests/unit/plugins/modules/test_ome_identity_pool.py
Labels: validation/completed, Ready for PR review

#964 [Module][ome_job_info]: qualification changes
  docs/modules/ome_job_info.rst
  plugins/modules/ome_job_info.py
  tests/unit/plugins/modules/test_ome_job_info.py
Labels: validation/completed, Ready for PR review

#950 [role][redfish_firmware] : 17G qual
  plugins/modules/redfish_firmware.py
  roles/redfish_firmware/molecule/_wait_for_idrac_interface.yml
  roles/redfish_firmware/molecule/negative_scenarios-10598/converge.yml
Labels: validation/completed, Ready for PR review, Next Month Milestones

#970 [module][ome_profile] Qualification ansible 2.19
  playbooks/ome/profile/ome_profile.yml
  playbooks/ome/profile/ome_profile_assign_job_tracking.yml
  playbooks/ome/profile/ome_profile_migrate_job_tracking.yml
  playbooks/ome/profile/ome_profile_unassign_job_tracking.yml
  plugins/modules/ome_profile.py
  tests/unit/plugins/modules/test_ome_profile.py
Labels: Ready for PR review

#976 [Module][SCP] 17G Support
  .gitignore
  Makefile
  plugins/module_utils/idrac_redfish.py
  plugins/modules/idrac_network_attributes.py
  plugins/modules/idrac_server_config_profile.py
  pytest.ini
  test-requirements.txt
  tests/integration/targets/idrac_server_config_profile/defaults/main.yaml
  tests/integration/targets/idrac_server_config_profile/files/ansible_doc.txt
  tests/integration/targets/idrac_server_config_profile/files/import_custom_default.xml
  tests/integration/targets/idrac_server_config_profile/files/pre_req_import_custom_default.xml
  tests/integration/targets/idrac_server_config_profile/files/preview_test.json
  tests/integration/targets/idrac_server_config_profile/files/preview_test.xml
  tests/integration/targets/idrac_server_config_profile/meta/main.yaml
  tests/integration/targets/idrac_server_config_profile/tasks/main.yaml
  tests/integration/targets/idrac_server_config_profile/tests/_export_http.yml
  tests/integration/targets/idrac_server_config_profile/tests/_export_https.yml
  tests/integration/targets/idrac_server_config_profile/tests/_get_idrac_settings.yml
  tests/integration/targets/idrac_server_config_profile/tests/_idrac_job_wait.yml
  tests/integration/targets/idrac_server_config_profile/tests/_import_http.yml
  tests/integration/targets/idrac_server_config_profile/tests/_import_scp_no_proxy.yml
  tests/integration/targets/idrac_server_config_profile/tests/_preview_file_cnfs.yml
  tests/integration/targets/idrac_server_config_profile/tests/_preview_file_http.yml
  tests/integration/targets/idrac_server_config_profile/tests/_preview_with_import_buffer.yml
  tests/integration/targets/idrac_server_config_profile/tests/_scp_file_verify.yml
  tests/integration/targets/idrac_server_config_profile/tests/ansible_doc-11771.yaml
  tests/integration/targets/idrac_server_config_profile/tests/export_cifs-11763.yaml
  tests/integration/targets/idrac_server_config_profile/tests/export_http-11764.yaml
  tests/integration/targets/idrac_server_config_profile/tests/export_https-11765.yaml
  tests/integration/targets/idrac_server_config_profile/tests/export_local-11761.yaml
  tests/integration/targets/idrac_server_config_profile/tests/export_nfs-11762.yaml
  tests/integration/targets/idrac_server_config_profile/tests/get_data.yml
  tests/integration/targets/idrac_server_config_profile/tests/import_cifs-11768.yaml
  tests/integration/targets/idrac_server_config_profile/tests/import_http-11769.yaml
  tests/integration/targets/idrac_server_config_profile/tests/import_https-11770.yaml
  tests/integration/targets/idrac_server_config_profile/tests/import_local-11766.yaml
  tests/integration/targets/idrac_server_config_profile/tests/import_nfs-11767.yaml
  tests/integration/targets/idrac_server_config_profile/tests/import_with_import_buffer-11775.yaml
  tests/integration/targets/idrac_server_config_profile/tests/invalid_custom_default-11779.yaml
  tests/integration/targets/idrac_server_config_profile/tests/invalid_export-11772.yaml
  tests/integration/targets/idrac_server_config_profile/tests/invalid_import-11773.yaml
  tests/integration/targets/idrac_server_config_profile/tests/invalid_preview-11776.yaml
  tests/integration/targets/idrac_server_config_profile/tests/preview_file-11777.yaml
  tests/integration/targets/idrac_server_config_profile/tests/preview_with_import_buffer-11774.yaml
  tests/integration/targets/idrac_server_config_profile/tests/valid_custom_default-11778.yaml
  tests/unit/plugins/module_utils/test_idrac_redfish.py
  tests/unit/plugins/modules/test_idrac_server_config_profile.py
Labels: validation/completed, Ready for PR review

#975 [Module][iDRAC Storage Volume]: 17G qual
  docs/modules/idrac_storage_volume.rst
  plugins/modules/idrac_redfish_storage_controller.py
  plugins/modules/idrac_storage_volume.py
  tests/integration/targets/idrac_storage_volume/defaults/main.yaml
  tests/integration/targets/idrac_storage_volume/files/ansible_doc.txt
  tests/integration/targets/idrac_storage_volume/meta/main.yaml
  tests/integration/targets/idrac_storage_volume/tasks/main.yaml
  tests/integration/targets/idrac_storage_volume/tests/_create_dhs_VD.yml
  tests/integration/targets/idrac_storage_volume/tests/_create_raids.yml
  tests/integration/targets/idrac_storage_volume/tests/_create_vd_with_invalid_physical_disks.yml
  tests/integration/targets/idrac_storage_volume/tests/_fetch_controller_drives.yml
  tests/integration/targets/idrac_storage_volume/tests/_fetch_volume_details.yml
  tests/integration/targets/idrac_storage_volume/tests/_pre_req_delete_view.yml
  tests/integration/targets/idrac_storage_volume/tests/_reset_config.yml
  tests/integration/targets/idrac_storage_volume/tests/_single_volume_create_verify.yml
  tests/integration/targets/idrac_storage_volume/tests/_validation_span_length_and_span_depth_verify.yml
  tests/integration/targets/idrac_storage_volume/tests/_view_api_output.yml
  tests/integration/targets/idrac_storage_volume/tests/ansible_doc-11799.yaml
  tests/integration/targets/idrac_storage_volume/tests/delete_VDs-11796.yaml
  tests/integration/targets/idrac_storage_volume/tests/dhs_single_raid-11802.yaml
  tests/integration/targets/idrac_storage_volume/tests/invalid_common_params-11800.yaml
  tests/integration/targets/idrac_storage_volume/tests/invalid_delete_VDs-11801.yaml
  tests/integration/targets/idrac_storage_volume/tests/invalid_span_length_and_span_depth-11805.yaml
  tests/integration/targets/idrac_storage_volume/tests/invalid_view-11794.yaml
  tests/integration/targets/idrac_storage_volume/tests/multi_raids_dhs-11793.yaml
  tests/integration/targets/idrac_storage_volume/tests/multi_raids_diff_params-11798.yaml
  tests/integration/targets/idrac_storage_volume/tests/multi_raids_jobwait_false-11795.yaml
  tests/integration/targets/idrac_storage_volume/tests/raid0-11803.yaml
  tests/integration/targets/idrac_storage_volume/tests/raid1-11806.yaml
  tests/integration/targets/idrac_storage_volume/tests/raid10-11787.yaml
  tests/integration/targets/idrac_storage_volume/tests/raid5-11807.yaml
  tests/integration/targets/idrac_storage_volume/tests/raid50-11789.yaml
  tests/integration/targets/idrac_storage_volume/tests/raid6-11808.yaml
  tests/integration/targets/idrac_storage_volume/tests/raid60-11791.yaml
  tests/integration/targets/idrac_storage_volume/tests/raid_init_check.yml
  tests/integration/targets/idrac_storage_volume/tests/raid_reset_and_create_new_VD-11804.yaml
  tests/integration/targets/idrac_storage_volume/tests/validate_incorrect_physical_disks-TC-11797.yaml
  tests/integration/targets/idrac_storage_volume/tests/view_no_controller-11788.yaml
  tests/integration/targets/idrac_storage_volume/tests/view_volume_specific-11792.yaml
  tests/integration/targets/idrac_storage_volume/tests/view_when_controller-11790.yaml
  tests/integration/targets/idrac_storage_volume/vars/main.yaml
Labels: validation/completed, Ready for PR review

#977 [Module][idrac_os_deployment]: 17G support
  docs/modules/idrac_os_deployment.rst
  plugins/modules/idrac_os_deployment.py
  tests/integration/targets/idrac_os_deployment/defaults/main.yaml
  tests/integration/targets/idrac_os_deployment/files/ansible_doc.txt
  tests/integration/targets/idrac_os_deployment/meta/main.yaml
  tests/integration/targets/idrac_os_deployment/tasks/main.yaml
  tests/integration/targets/idrac_os_deployment/tests/_helper.yml
  tests/integration/targets/idrac_os_deployment/tests/ansible_doc-11720.yaml
  tests/integration/targets/idrac_os_deployment/tests/invalid-11721.yaml
  tests/integration/targets/idrac_os_deployment/tests/osd-11719.yaml
  tests/integration/targets/idrac_os_deployment/vars/main.yml
  tests/unit/plugins/modules/test_idrac_os_deployment.py
Labels: Ready for PR review

#953 [Module][Redfish firmware rollback] 17G support added
  playbooks/redfish/firmware/redfish_firmware_rollback.yml
  plugins/module_utils/utils.py
  plugins/modules/redfish_firmware_rollback.py
  tests/integration/targets/idrac_redfish_firmware_rollback/tests/_assert_job_status.yml
  tests/integration/targets/idrac_redfish_firmware_rollback/tests/_get_job_details.yml
  tests/integration/targets/idrac_redfish_firmware_rollback/tests/_get_server_generation.yml
  tests/integration/targets/idrac_redfish_firmware_rollback/tests/all_except_bios-11897.yaml
  tests/integration/targets/idrac_redfish_firmware_rollback/tests/all_regex-11898.yaml
  tests/integration/targets/idrac_redfish_firmware_rollback/tests/bios-11893.yaml
  tests/integration/targets/idrac_redfish_firmware_rollback/tests/comp_no_available_version-11895.yaml
  tests/integration/targets/idrac_redfish_firmware_rollback/tests/idrac-11892.yaml
  tests/integration/targets/idrac_redfish_firmware_rollback/tests/idrac_bios_regex-11894.yaml
  tests/integration/targets/idrac_redfish_firmware_rollback/tests/invalid_attributes-11890.yaml
  tests/integration/targets/idrac_redfish_firmware_rollback/tests/invalid_reboot-11891.yaml
  tests/integration/targets/idrac_redfish_firmware_rollback/tests/network_regex-11896.yaml
  tests/unit/plugins/modules/test_redfish_firmware_rollback.py
Labels: validation/completed, Ready for PR review
